# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requireAdminNotify: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 #20 hrs
    - !type:OverallPlaytimeRequirement
      time: 108000 #30 hrs
    - !type:AgeRequirement
      requiredAge: 21 # cats
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: true # Ganimed MRP
  antagAdvantage: 5 # Ganimed MRP
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 600
  maxBankBalance: 800
  wageDepartment: Command
  wage: 200
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - CentralCommand
    - type: CommandStaff
    #start-backmen: surgery
    #- type: CPRTraining
    - type: SurgerySpeedModifier
      SpeedModifier: 2.5
    #end-backmen: surgery

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMilitaryWebbingCMOFilled # Goobstation
  storage:
    back:
    - Flash
