- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h # Corvax-RoleTime
  discordRequired: false # backmen: antag

- type: antag
  id: XenoAgent
  name: roles-antag-XenoAgent-name
  antagonist: true
  setPreference: false
  objective: roles-antag-XenoAgent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h
  discordRequired: false # backmen: antag
