- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Engineering
#      time: 54000 #15 hrs
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 54000 #15 hrs
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 90000 # 25 hours
    - !type:OverallPlaytimeRequirement
      time: 360000 #100 hrs
    - !type:AgeRequirement
      requiredAge: 24 # cats
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  #start-backmen: currency
  minBankBalance: 600
  maxBankBalance: 900
  wageDepartment: Command
  wage: 250
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CentralCommand
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    id: CaptainPDA
    #eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
