- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
#   - !type:DepartmentTimeRequirement
#     department: Engineering
#     time: 72000 #20 hrs # Corvax-RoleTime
#   - !type:DepartmentTimeRequirement
#     department: Medical
#     time: 72000 #20 hrs # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 18000 #5 hrs Ganimed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 90000 # 25 hrs Ganimed-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 360000 #100 hrs Ganimed-RoleTime
    - !type:TraitsRequirement # Ganimed-MRP: Captain must be proficient in communication
      inverted: true
      traits:
#     - Monolingual
      - Muted
      - Deaf
  # ADT Restrict Start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
  # ADT RESTRICT End
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - ADTAccessCaptain #ADT-tweak - полный доступ ко всем станционным дверям, кроме ЦК и ОСЩ
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom
      - type: AntagImmune # Ganimed-MRP: Loyalty implant

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
    # - StationCharter
