- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Engineering
#      time: 18000 #5 hrs # Corvax-RoleTime
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 18000 #5 hrs # Corvax-RoleTime
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 18000 #5 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 #15 hrs Ganimed-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 180000 #50 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 36000 #10 hrs Ganimed-RoleTime
#       ADT tweak start
#    - !type:SpeciesRequirement
#      inverted: true
#      species:
#      - Vox
#       ADT tweak end
  weight: 20
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  canBeAntag: true # Ganimed-MRP
  antagAdvantage: 5 # Ganimed-MRP
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
#  - !type:AddImplantSpecial # Ganimed-MRP
#    implants: [ MindShieldImplant ] # Ganimed-MRP
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: HoPGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
