- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 25200 #7 hrs
    - !type:AgeRequirement
      requiredAge: 21 # Ganimed-MRP
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
    - Medical
    - Security
    - Brig
    - Maintenance
    - External
  extendedAccess:
    - Cryogenics
  #start-backmen: currency
  minBankBalance: 200
  maxBankBalance: 400
  wageDepartment: Security
  wage: 100
  #end-backmen: currency
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
