- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requireAdminNotify: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 54000 #15 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #30 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
    - !type:AgeRequirement
      requiredAge: 24 # cats
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 600
  maxBankBalance: 800
  wageDepartment: Command
  wage: 200
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: NpcFactionMember
        factions:
          - CentralCommand

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    ears: ClothingHeadsetAltSecurity
  storage:
    back:
    - Flash
    #- SecHypo # Cats edit
