- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs Ganimed-RoleTime
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 72000 #20 hrs # Corvax-RoleTime
#      inverted: true # stop playing intern if you're good at security!
#    ADT Restrict Start
#    - !type:SpeciesRequirement # Ganimed-Tweak
#      inverted: true
#      species:
#      - Resomi
#      - Vox
#      - Shadekin
#    ADT RESTRICT End
    - !type:AgeRequirement
      inverted: true
      requiredAge: 100 # Ganimed-MRP
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  extendedAccess: # Ganimed Tweak: Cadet access
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: BookSecurity # Ganimed-Tweak
  storage:
    back:
    - Flash
    - MagazinePistol
