# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: BackmenAmmoStatic
  recipes:
    - MagazineBoxLightRifle
    - MagazineBoxMagnum
    - MagazineBoxPistol
    - MagazineBoxRifle
    - MagazineLightRifle

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: BackmenAmmo
  recipes:
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxMagnumIncendiary
  - MagazineBoxPistolIncendiary
  - MagazineBoxRifleIncendiary
  - MagazineGrenadeEmpty
  - MagazineLightRifleIncendiary
  - MagazinePistolIncendiary
  - MagazineRifleIncendiary
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - MagazineShotgunIncendiary
  - BoxShotgunIncendiary
  - MagazinePistolSubMachineGunIncendiary
  - SpeedLoaderMagnumIncendiary
  - BoxShellTranquilizer
  - BoxBeanbag
  - SpeedLoaderMagnumUranium
  - BoxShotgunUranium
