contact_links:
  - name: Предложение
    url: https://discord.com/invite/nCn5F3kNyH
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.com/invite/nCn5F3kNyH
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности mathemat1ka (571697093618565132) в Discord.
