- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 21600 #6 hrs #Ganimed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 #20 hrs Ganimed-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs Ganimed-RoleTime
#       ADT tweak start
#    - !type:SpeciesRequirement
#      inverted: true
#      species:
#      - Vox
#       ADT tweak end
    - !type:AgeRequirement # Ganimed-MRP
      requiredAge: 21
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  canBeAntag: true # Ganimed-MRP
  antagAdvantage: 5 # Ganimed-MRP: Heads can be antags
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
#  - !type:AddImplantSpecial # Ganimed-MRP
#    implants: [ MindShieldImplant ] # Ganimed-MRP
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    # eyes: ClothingEyesGlassesMeson #ADT-Tweak - заменено на выбор
    # ears: ClothingHeadsetCE # ADT tweak
# ADT-Tweak-start по причине того, что ассистент и остальной состав ИО спавнится с двумя поясами, если их выбрать в лоудауте
    # belt: ClothingBeltUtilityEngineering
# ADT-Tweak-end
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
