- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requireAdminNotify: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 #20 hrs
    - !type:OverallPlaytimeRequirement
      time: 108000 #30 hrs
    - !type:AgeRequirement
      requiredAge: 21 # cats
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  canBeAntag: true # Ganimed MRP
  antagAdvantage: 5 # Ganimed MRP
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 600
  maxBankBalance: 800
  wageDepartment: Command
  wage: 200
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CentralCommand
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    #eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Flash
