- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - ENTRBox
  - Cog
  - Core
  - Elkridge
  - Fland
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Plasma
  - Reach
  - Cluster
  #- Train
