- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  # ADT-Tweak-start
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 #1 hr #Ganimed-RoleTime
  # ADT-tweak-end
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    # shoes: ClothingShoesLeather # Ganimed-Loadouts
    # id: PsychologistPDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist

- type: chameleonOutfit
  id: PsychologistChameleonOutfit
  job: Psychologist
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    outerClothing: ClothingOuterCoatLab
    neck: ClothingNeckStethoscope
    belt: ClothingBeltMedical
    gloves: ClothingHandsGlovesLatex
