- type: job
  id: SecurityEngineer
  name: job-name-security-engineer
  description: job-description-security-engineer
  playTimeTracker: JobSecurityEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 #6 hrs
    - !type:AgeRequirement
      requiredAge: 20 # Ganimed-MRP
  startingGear: SecurityEngineerGear
  icon: "JobIconSecurityEngineer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Engineering
  #start-backmen: currency
  minBankBalance: 200
  maxBankBalance: 400
  wageDepartment: Security
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecEngineer
    back: ClothingBackpackSecurityEngineer
    shoes: ClothingShoesBootsJackSecEngineer
    eyes: ClothingEyesHudSecEng
    id: SecurityEngineerPDA
    suitstorage: SecBreachingHammer
    ears: ClothingHeadsetSecurityEngineer
    belt: ClothingMilitaryWebbingSecEng
  storage:
    back:
    - SecRCD
    - RCDAmmo
    - RCDAmmo
    - LPPC4Low
    - LPPC4Low