- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
#  requirements: # Ganimed-Tweak
#    - !type:OverallPlaytimeRequirement
#      time: 14400 # ADT-PlaytimeRequirement = 4 hrs
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard
  alternateTitles: # Ganimed-JobAlt
  - CargoTechnitianTitleWtf

- type: startingGear
  id: CargoTechGear
  equipment:
    #id: CargoPDA # ADT: different PDAs in loadouts
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff

  # Ganimed-JobAlt
- type: jobAlternateTitle
  id: CargoTechnitianTitleWtf
  name: job-name-alt-cargo-wtf