- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 21600 #6 hrs # Ganimed-RoleTime
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 21600 #6 hrs # Ganimed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 72000 #20 hours # Ganimed-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 126000 #35 hrs # Ganimed-RoleTime
      #ADT tweak start
#    - !type:SpeciesRequirement
#      inverted: true
#      species:
#      - Vox
      #ADT tweak end
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-hop # Ganimed-MRP, test merge
  canBeAntag: true # Ganimed-MRP
  #antagAdvantage: 5 # Ganimed-MRP, no advantage during the test merge
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
#  - Command # Ganimed-MRP, test merge
#  - Brig # Ganimed-MRP, test merge
  - Cryogenics
#  special:
#  - !type:AddImplantSpecial # Ganimed-MRP
#    implants: [ MindShieldImplant ] # Ganimed-MRP
#  - !type:AddComponentSpecial # Ganimed-MRP, test merge
#    components: # Ganimed-MRP, test merge
#      - type: CommandStaff # Ganimed-MRP, test merge
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    # ears: ClothingHeadsetQM # ADT tweak
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
