- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 18000 #5 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 72000 #20 hrs
    - !type:OverallPlaytimeRequirement
      time: 108000 #30 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Cargo
  wage: 150
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: NpcFactionMember
        factions:
          - CentralCommand

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
