- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
#    - !type:RoleTimeRequirement
#      role: JobCargoTechnician
#      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
      #ADT tweak start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Vox
      #ADT tweak end
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-hop # Ganimed-MRP, test merge
  canBeAntag: true # Ganimed-MRP
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
#  - Command # Ganimed-MRP, test merge
#  - Brig # Ganimed-MRP, test merge
  - Cryogenics
  special:
#  - !type:AddImplantSpecial # Ganimed-MRP
#    implants: [ MindShieldImplant ] # Ganimed-MRP
#  - !type:AddComponentSpecial # Ganimed-MRP, test merge
#    components: # Ganimed-MRP, test merge
#      - type: CommandStaff # Ganimed-MRP, test merge
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
