# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 72000 #20 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitOld
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSOld

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

- type: loadout # Ganimed TODO: Whitelist restriction
  id: HeadofSecurityCloakLong
  equipment:
    neck: ClothingLongCloakHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

- type: loadout
  id: ClothingOuterWinterSeniorOfficer
  equipment:
    outerClothing: ClothingOuterWinterSeniorOfficer  # cats

- type: loadout # Ganimed
  id: HeadofSecurityUnarmoredWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoSUnarmored

- type: loadout # Ganimed
  id: HeadofSecurityTrenchCoat
  equipment:
    outerClothing: Clothinghoscoat

# Pocket #Backmen

- type: loadout
  id: WeaponRevolverMatebaNew
  equipment:
    pocket1: WeaponRevolverMatebaNew

# Pocket 2 #Backmen

- type: loadout
  id: SpeedLoaderMagnum
  equipment:
    pocket2: SpeedLoaderMagnum
