# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 72000 #20 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitOld
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSOld

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue

- type: loadout # Ganimed
  id: HeadofSecurityJumpsuitOriginal
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSOriginal

- type: loadout # Ganimed
  id: HeadofSecurityJumpskirtOriginal
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSOriginal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

- type: loadout # Ganimed TODO: Whitelist restriction
  id: HeadofSecurityLeatherCap
  equipment:
    head: ClothingHeadHatCapHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

- type: loadout # Ganimed
  id: HeadofSecurityShoulderMantle
  equipment:
    neck: ClothingNeckMantleHOSShoulder

- type: loadout # Ganimed TODO: Whitelist restriction
  id: HeadofSecurityCloakLong
  equipment:
    neck: ClothingLongCloakHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout # Ganimed
  id: HeadofSecurityBedsheet
  equipment:
    neck: BedsheetHOS

# Back, Ganimed
- type: loadout # TODO: Whitelist restriction
  id: HeadofSecuritySatchel
  whitelisted: true
  equipment:
    back: ClothingBackpackSatchelHoS

# Belt, Ganimed
- type: loadout # TODO: Whitelist restriction
  id: HeadofSecurityLeatherBelt
  equipment:
    belt: ClothingBeltHoS

# Gloves, Ganimed
- type: loadout
  id: CombatGloves
  equipment:
    gloves: ClothingHandsGlovesCombat

- type: loadout # TODO: Whitelist restriction
  id: HeadofSecurityLeatherGloves
  equipment:
    gloves: ClothingHandsGlovesLeatherHoS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

- type: loadout # Ganimed
  id: HeadofSecurityUnarmoredWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoSUnarmored

- type: loadout # Ganimed
  id: HeadofSecurityTrenchCoat
  equipment:
    outerClothing: Clothinghoscoat

# Pocket #Backmen
- type: loadout
  id: WeaponRevolverMatebaNew
  equipment:
    pocket1: WeaponRevolverMatebaNew

# Pocket 2 #Backmen
- type: loadout
  id: SpeedLoaderMagnum
  equipment:
    pocket2: SpeedLoaderMagnum
