[game]
hostname = "[RU][MRP] 🚀 Enterprise — Новое путешествие"
desc = "Enterprise — ламповый, ориентированный на сообщество сервер, с приятной игровой атмосферой, уникальными фишками, насыщенными раундами и повышенным уровнем РП. \nОтзывчивая администрация, дружелюбная к новичкам, может помочь вам на любом этапе игры! \nЧто вы можете получить, играя у нас?\n ╭ 🔥 Chaotic-Medium — баланс между хаотичными и спокойными раундами;\n ┃ 🔩 Мехи и лаваленд;\n ┃ 🔪 Проработанный лор, на основе которого проводятся ивенты;\n ┃ 👥 Особенные игровые роли с широкой возможностью персонализации;\n ┃ ✨ Множество играбельных рас и уникальных антагонистов.\n ╰ 🔘 Это и многое другое на Enterprise!"
maxplayers = 60
soft_max_players = 50
map_rotation = true
fallbackpreset = "extended"
lobbyenabled = true
role_timers = true
contraband_examine = false
lobbyduration = 300

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 256

[shuttle]
auto_call_time = 180
emergency_early_launch_allowed = true

[infolinks]
discord = "https://discord.gg/5JdpCD9rqM"
github = "https://github.com/CrimeMoot/Ganimed14/"
wiki = "https://station-enterprise.space"
patreon = "https://boosty.to/enterprisess14"
appeal = "https://discord.gg/5JdpCD9rqM"
bug_report = "https://github.com/CrimeMoot/Ganimed14/issues/new/choose"
website = "https://station-enterprise.space"

[server]
lobby_name = "️Enterprise — Новое путешествие!"
rules_file = "GanimedRuleset"

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
preset_enabled = false
restart_enabled = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 10
min_overall_minutes = 0
# deny_vpn = false
enable_without_admins = true
disable_with_admins = true

[atmos]
space_wind = true

[ic]
flavor_text = true

[discord]
ahelp_webhook = "*"
ahelp_avatar = "*"
round_update_webhook = "*"
round_end_role = "*"
ban_webhook = "*"

[rules]
time = 60

[admin]
admins_count_in_playercount = true
admins_count_for_max_players = true
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 1440

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"
server_url = "*"
hub_urls = "https://hub.spacestation14.com/"

[sponsor]
api_url = "http://80.87.197.41:8081/api"