- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs
  - !type:AgeRequirement
    requiredAge: 20 # Ganimed-MRP
  startingGear: PilotGear
  icon: "JobIconPilot"
  supervisors: job-supervisors-hos
  canBeAntag: false
  #start-backmen: currency
  minBankBalance: 1500
  maxBankBalance: 2500
  wageDepartment: Security
  wage: 500
  #end-backmen: currency
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PilotGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    id: PilotPDA
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckTieRed
  storage:
    back:
    - Flash
