- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 90000 # 25 hrs Ganimed-RoleTime
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Start ADT Tweak
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # Ganimed-MRP: Loyalty implant
    components:
      - type: AntagImmune
  # End ADT Tweak

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorCentcommCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
  storage:
    back:
    - Flash #ADT-CustomADTLoadout
    - ADTtelescopicBaton #ADT-CustomADTLoadout


- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
