- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Silicon
      time: 18000 #5 hrs
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  #- Robotics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Science
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: RoboticistGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: RoboticistPDA
    ears: ClothingHeadsetRobotics
    belt: ClothingBeltUtilityFilled
  #eyes: ClothingEyesGlassesWelding
  #innerClothingSkirt: ClothingUniformJumpskirtRoboticist
  #satchel: ClothingBackpackSatchelScienceFilled
  #duffelbag: ClothingBackpackDuffelScienceFilled
