- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds

- type: startingGear
  id: BotanistGear
  equipment:
    # shoes: ClothingShoesColorBrown # Ganimed-Loadouts
    # id: BotanistPDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetService
    # belt: ClothingBeltPlantFilled # Ganimed-Loadouts
  #storage:
    #back:
    #- Stuff
