- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-iaa
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
    #ADT tweak start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Vox
      #ADT tweak end
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-magistrate
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    # id: LawyerPDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetLawyer
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw
