# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:DepartmentTimeRequirement
    department: Silicon
    time: 54000 # 15 hrs Ganimed-RoleTime
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  containerInsert: true # ADT station AI spawn fix
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false
  # ADT SAI Custom start
  loadoutOverride: StationAILoadoutWindow
  loadoutButtonText: Customize
  # ADT SAI Custom end

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs Ganimed-RoleTime
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
