- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 21600 #6 hrs #Ganimed-RoleTime
  - !type:DepartmentTimeRequirement
    department: Science
    time: 72000 #20 hrs Ganimed-RoleTime
  - !type:OverallPlaytimeRequirement
    time: 126000 #35 hrs Ganimed-RoleTime
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: true # Ganimed-MRP: Heads can be antags
  antagAdvantage: 5 # Ganimed-MRP
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
#  - !type:AddImplantSpecial # Ganimed-MRP: Heads can be antags
#    implants: [ MindShieldImplant ] # Ganimed-MRP
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: ResearchDirectorGear
  equipment:
 #id: RnDPDA # ADT Tweak
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
