- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  canBeAntag: false
  requireAdminNotify: true
  joinNotifyCrew: true
  discordRequired: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 14400 #4 hrs
    - !type:OverallPlaytimeRequirement
      time: 86400 #24 hrs
    - !type:AgeRequirement
      requiredAge: 21 # cats
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: CommandStaff
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: AntagImmune
  startingGear: BlueShieldGear
  icon: "JobIconBlueShield"
  supervisors: job-supervisors-hoh
  accessGroups:
    - AllAccessWithOutHeads
  access:
    - CCOfficer
    - CentralCommand
  #start-backmen: currency
  minBankBalance: 900
  maxBankBalance: 1600
  wageDepartment: CentralCommand
  wage: 200
  #end-backmen: currency

- type: startingGear
  id: BlueShieldGear
  equipment:
    id: BlueShieldPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltCommand
    shoes: ClothingShoesBootsCombat
    back: ClothingBlueshieldBackpack # cats
    belt: ClothingBeltSecurityCentComSecurity
    pocket1: PistolBlueShield # cats
  storage:
    back:
  #  - BlueShieldLoadout
    - BlueShieldSetMedical
    - CombatKnifeSpetsnaz
    - SecHypo
