name: Build & Test Debug Linux # ADT-Tweak

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]
  workflow_dispatch: # ручной запуск ADT Tweak

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    if: github.actor != 'IanComradeBot' && github.event.pull_request.draft == false
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Master
      uses: actions/checkout@v4.2.2

    - name: Setup Submodule
      run: |
        git submodule update --init --recursive

    - name: Pull engine updates
      uses: space-wizards/submodule-dependency@v0.1.5

    - name: Update Engine Submodules
      run: |
        cd RobustToolbox/
        git submodule update --init --recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m

    - name: Run Content.Tests
      run: dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0

    - name: Run Content.IntegrationTests
      shell: bash
      run: |
        echo "🟡 Запуск интеграционных тестов..."
        sleep 2
        DOTNET_gcServer=1 dotnet test \
          --no-build \
          --configuration DebugOpt \
          Content.IntegrationTests/Content.IntegrationTests.csproj \
          -- NUnit.ConsoleOut=0 NUnit.MapWarningTo=Failed \
          > integration-tests.log 2>&1 || {
            echo "❌ Тесты завершились с ошибкой:"
            cat integration-tests.log
            exit 1
          }
        echo "✅ Интеграционные тесты завершены успешно."
        cat integration-tests.log

  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
