name: Check FTL Duplicates

on:
  push:
    branches: [ master, staging, stable ]
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  check-ftl-duplicates:
    name: Check FTL Duplicates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run FTL duplicates check
        run: |
          python Tools/ganimed/check_ftl_duplicates.py