name: Localization Check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  locale-check:
    name: Check Localization Files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install googletrans==4.0.0-rc1

      - name: Run localization check
        run: python3 Tools/ganimed/locale_check_ftl.py

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes if any
        run: |
          git add Resources/Locale/ru-RU
          git diff --cached --quiet || (git commit -m "Auto-translate missing locale strings" && git push)